<a href="https://colab.research.google.com/github/Sohith-Pothula/My-Data-Science-Journey/blob/main/NumPy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
#a = np.array([[1,2,4,5],[563,678,673,885]])

In [9]:
a

array([[  1,   2,   4,   5],
       [563, 678, 673, 885]])

In [11]:
a1=np.array([1,2,3,4])#1d array
a1

array([1, 2, 3, 4])

In [12]:
a2 = np.array([[1,2,3,4],[6,7,8,9]])#2d arrays
a2

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [13]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full((5,6),3)

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.arange(1,10,3)

array([1, 4, 7])

In [29]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [32]:
np = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2],[4,5,6,7]])

In [33]:
np

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2],
       [4, 5, 6, 7]])

In [34]:
np.shape

(4, 4)

In [35]:
np.ndim

2

In [36]:
np.size

16

In [37]:
np.dtype

dtype('int64')