In [1]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np 

In [3]:
arr1=np.array(45)

In [4]:
print(arr1)

45


In [8]:
arr2=np.array([[45,78,23,45],[45,78,32,65]])

In [9]:
print(arr2)

[[45 78 23 45]
 [45 78 32 65]]


In [10]:
print(arr2.shape)

(2, 4)


In [11]:
print(arr2.size)

8


In [12]:
print(arr2.dtype)

int64


In [14]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6]) 

In [16]:
print(a+b)
print(a-b)
print(a*b)
print(np.dot(a, b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
32


In [21]:
arr = np.arange(1, 10) 

In [22]:
print(arr.reshape(3, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
arr = np.array([10, 20, 30, 40]) 

In [25]:
print(np.sum(arr)) 
print(np.mean(arr))
print(np.std(arr))  
print(np.max(arr))
print(np.min(arr))

100
25.0
11.180339887498949
40
10


In [26]:
print(np.random.rand(3, 3))

[[0.57406801 0.73147171 0.0420007 ]
 [0.99066678 0.18720993 0.90275522]
 [0.24574254 0.50749318 0.43312307]]


In [27]:
print(np.random.randint(1, 100, (3, 3)) )

[[90 89 52]
 [49  4 88]
 [34  3 73]]


In [28]:
arr = np.array([10, 20, 30, 40])
print(arr[0])  
print(arr[-1]) 

10
40


In [29]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  
print(arr[:3])  
print(arr[::2])  

[20 30 40]
[10 20 30]
[10 30 50]


In [30]:
arr = np.array([1.5, 2.7, 3.9])
print(arr.dtype)  # Output: float64

arr_int = arr.astype(np.int32)
print(arr_int)   
print(arr_int.dtype)  

float64
[1 2 3]
int32


In [31]:
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10') 
print(arr)

['apple' 'banana' 'cherry']


In [32]:
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']
